### ISSUE TITLE
Error Removing .webpack

### ISSUE THREAD

**Issue by ncipollina** [Dynatrace/serverless-oneagent#16]
Every time I try to do a serverless deploy with this module included, I get the following error:

```
  Error --------------------------------------------------
 
  Error: EBUSY: resource busy or locked, rmdir 'C:\source\repos\b2cs\user-services\api\.webpack\dependencies'
      at Object.rmdirSync (fs.js:684:3)
      at rmdirSync (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:276:13)
      at rimrafSync (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
      at options.readdirSync.forEach.f (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
      at rmdirSync (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
      at Object.rimrafSync (C:\source\repos\b2cs\user-services\api\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
      at processConfig (C:\source\repos\b2cs\user-services\api\node_modules\serverless-webpack\lib\validate.js:161:13)
      at ServerlessWebpack.validate (C:\source\repos\b2cs\user-services\api\node_modules\serverless-webpack\lib\validate.js:229:14)
      at ServerlessWebpack.tryCatcher (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\promise.js:517:31)
      at Promise._settlePromise (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\promise.js:574:18)
      at Promise._settlePromiseCtx (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\promise.js:611:10)
      at _drainQueueStep (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\async.js:142:12)
      at _drainQueue (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\async.js:131:9)
      at Async._drainQueues (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\source\repos\b2cs\user-services\api\node_modules\bluebird\js\release\async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.16.0
     Framework Version:         1.53.0
     Plugin Version:            3.1.1
     SDK Version:               2.1.1
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

I turned on verbose and I think the issue is because it uses this configuration:

```

Serverless: Using configuration:
{
  "includeModules": {
    "forceInclude": [
      "@dynatrace/oneagent"
    ]
  },
  "webpackConfig": "webpack.config.js",
  "packager": "npm",
  "packagerOptions": {},
  "keepOutputDirectory": false
}

```

Any way to change `keepOutputDirectory` to `true`? And if so, would that fix my issue?

**Comment by Hollerberg** [comment]
Could you provide your (stripped down) serverless project to reproduce the issue? The plugin does modify the `keepOutputDirectory `option.

**Comment by Hollerberg** [comment]
Closing due to inactivity. Please feel free to reopen of the problem still persists.
