### ISSUE TITLE
Yarn deploy fails using serverless-oneagent

### ISSUE THREAD

**Issue by gbc921** [Dynatrace/serverless-oneagent#25]
Hi @Hollerberg, Claro is a customer that is trying to deploy the OneAgent with their lambda function.
However, they use Yarn as their package manager, which is causing error during deploying time.

The instructions that we followed were based [on npmjs documentation](https://www.npmjs.com/package/@dynatrace/serverless-oneagent#specify-oneagent-options), 
as well as [adding the Yarn configuration in this link](https://www.npmjs.com/package/@dynatrace/serverless-oneagent#yarn-configuration)

What seems to be happening is that npm install the oneagent dependency again, even after Yarn installing it, thus breaking the deploy.
We tried to execute [your comment here on the other ticket](https://github.com/Dynatrace/serverless-oneagent/issues/4#issuecomment-446278007), but the error is the same. Also, they use a CI/CD pipeline which makes manual commands harder to implement.

**Is there maybe any way/flag to ignore the oneagent install through npm again (as yarn already handles it)?**

When using only the npm, everything worked fine and we could see transactions in Dynatrace as well.

The debug log with the error is found below:
```
yarn run v1.21.0
$ sls deploy --stage development --claroenv prod --nockintercept false
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: [Dynatrace OneAgent] Installing Dynatrace oneagent npm module: @dynatrace/oneagent
+ @dynatrace/oneagent@1.191.239-1.0.0
removed 27 packages, updated 1 package and audited 1827 packages in 8.766s

34 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Serverless: [Dynatrace OneAgent] tailoring OneAgent module in ./
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  Error: ENOENT: no such file or directory, open '/Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/libcipm/node_modules/.bin/lock-verify'
      at Package.getFileContent (/Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/serverless/lib/plugins/package/lib/zipService.js:137:15)
      at Package.getFileContentAndStat (/Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/serverless/lib/plugins/package/lib/zipService.js:126:12)
      at Array.map (<anonymous>)
      at WriteStream.output.on (/Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/serverless/lib/plugins/package/lib/zipService.js:95:46)
      at WriteStream.emit (events.js:198:13)
      at WriteStream.EventEmitter.emit (domain.js:448:20)
      at /Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:306:14
      at /Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:333:16
      at /Users/nelson.prado/repositorios/monorepo/minha-claro/app-backend/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:258:16
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.20.1
     Framework Version:         1.58.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Hollerberg** [comment]
Dear @gbc921,
would it be possible to provide a stripped down example that reproduces the problem? Thanks!

**Comment by Hollerberg** [comment]
Moved to internal ticket
